# See: https://docs.microsoft.com/azure/devops/pipelines/yaml-schema
# See: https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
  workingDir: interfaces/AW-App/

trigger:
  branches:
    include:
      - master
      - release/*
  paths:
    include:
      - 'interfaces/AW-App/*'
pr:
  branches:
    include:
      - master
  paths:
    include:
      - 'interfaces/AW-App/*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'

  - script: npm ci
    displayName: Install
    workingDirectory: $(workingDir)

  - script: npm run lint
    displayName: Linting
    workingDirectory: $(workingDir)

  - script: npm test
    displayName: Tests
    workingDirectory: $(workingDir)

  - script: npm run build -- --prod
    displayName: Build Production-mode
    workingDirectory: $(workingDir)
