# See: https://docs.microsoft.com/azure/devops/pipelines/yaml-schema
# See: https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - 'interfaces/AW-App/*'
pr:
  branches:
    include:
    - master
  paths:
    include:
    - 'interfaces/AW-App/*'

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'

- script: npm ci
  displayName: Install
  workingDirectory: interfaces/AW-App/

- script: npm run lint
  displayName: Linting
  workingDirectory: interfaces/AW-App/

- script: npm test
  displayName: Tests
  workingDirectory: interfaces/AW-App/
