# See: https://docs.microsoft.com/azure/devops/pipelines/yaml-schema
# See: https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - master
      - release/*
  paths:
    include:
      - 'services/121-service/*'
pr:
  branches:
    include:
      - master
  paths:
    include:
      - 'services/121-service/*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'

  - script: npm ci
    displayName: Install
    workingDirectory: services/121-service/

  - script: npm test
    displayName: Tests
    workingDirectory: services/121-service/
    env:
      SECRETS_121_SERVICE_SECRET: test
      APPLICATION_INSIGHT_IKEY: test
      TWILIO_SID: ACtest
      TWILIO_AUTHTOKEN: test
      TWILIO_TEST_TO_NUMBER: test
      TWILIO_TEST_FROM_NUMBER_VOICE: test
      TWILIO_TEST_FROM_NUMBER_SMS: test
      INTERSOLVE_AUTH_TOKEN: test
      INTERSOLVE_PRODUCT_CODE: test
      INTERSOLVE_PACKAGE_CODE: test
      INTERSOLVE_USERNAME: test
      INTERSOLVE_PASSWORD: test
      INTERSOLVE_EAN: test
      INTERSOLVE_URL: test
      AFRICASTALKING_API_KEY: test
      AFRICASTALKING_USERNAME: test
      AFRICASTALKING_PRODUCT_NAME: test
      AFRICASTALKING_CURRENCY_CODE: test
