# See: https://docs.microsoft.com/azure/devops/pipelines/yaml-schema
# See: https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
  workingDir: interfaces/HO-Portal/
  npm_config_cache: $(Pipeline.Workspace)/.npm

trigger:
  branches:
    include:
      - master
      - release/*
  paths:
    include:
      - 'interfaces/HO-Portal/*'
pr:
  branches:
    include:
      - master
  paths:
    include:
      - 'interfaces/HO-Portal/*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'

  - task: Cache@2
    displayName: Cache npm
    inputs:
      key: 'npm | "$(Agent.OS)" | "$(workingDir)package-lock.json"'
      restoreKeys: |
        npm | "$(Agent.OS)"
      path: $(npm_config_cache)

  - script: npm ci
    displayName: Install
    workingDirectory: $(workingDir)

  - script: npm run lint
    displayName: Linting
    workingDirectory: $(workingDir)

  - script: npm test
    displayName: Tests
    workingDirectory: $(workingDir)

  - script: npm run build -- --prod
    displayName: Build Production-mode
    workingDirectory: $(workingDir)
