name: 'Run External Integration Test: Retry Failed Jobs'

on:
  push:
    branches:
      - Piotrk39/refactor.move-remaining-k6-test
  schedule:
    - cron: '42 1 * * 1-5'
  workflow_dispatch:

env:
  workingDirectory: services/121-service/

jobs:
  external-integration-test:
    runs-on: ubuntu-latest
    timeout-minutes: 90 # Set to 90 minutes as the test has a 60-minute timeout

    strategy:
      fail-fast: false
      matrix:
        include:
          - test_name: 'retryFailedJobsOnStartupDuringQueueProcessing.test.ts'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Set up Node.js version
        uses: actions/setup-node@v5
        with:
          node-version-file: '${{ env.workingDirectory }}/.node-version'
          cache: 'npm'
          cache-dependency-path: '${{ env.workingDirectory }}/package-lock.json'

      - name: Set ENV-variables for test-environment
        run: |
          cp ./services/.env.example services/.env
          grep -v "^#\|^$" services/.env.example >> $GITHUB_ENV

      - name: Install dependencies
        working-directory: ${{ env.workingDirectory }}
        run: npm ci

      - name: Run Services with Docker
        run: |
          npm run start:services:ci:production

      - name: Wait for services to be ready
        run: |
          timeout 90s sh -c 'until curl http://localhost:3000/api -I; do echo "Waiting for the 121-service to be running..."; sleep 1; done'

      - name: Run external integration test - ${{ matrix.test_name }}
        working-directory: ${{ env.workingDirectory }}
        env:
          EXTERNAL_121_SERVICE_URL: http://localhost:3000
        run: |
          npm run test:integration:all -- test/performance/external/${{ matrix.test_name }}

      - name: Docker logs
        if: always()
        uses: jwalton/gh-docker-logs@v2
